### ISSUE TITLE
version 20210226 (but not 20210223) causes sage test failures

### ISSUE THREAD

**Issue by collares** [JohnCremona/eclib#64] opened 2021-03-01 15:55 UTC
The error log is as follows:

```
sage -t --long --random-seed=0 /nix/store/k9x5qwik8cdr9vm782v5ha116j097qn4-sage-src-9.2/src/sage/schemes/elliptic_curves/ell_rational_field.py
**********************************************************************
File "/nix/store/k9x5qwik8cdr9vm782v5ha116j097qn4-sage-src-9.2/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 1877, in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
Failed example:
    r, s, G = E.simon_two_descent(); r,s
Expected:
    (8, 8)
Got:
    After 10 attempts at enlargement, giving up!
    --points not proved 5-saturated,
    5-saturation failed!
    Failed to saturate MW basis at primes [ 5 ]
    5 After 10 attempts at enlargement, giving up!
    --points not proved 5-saturated,
    5-saturation failed!
    Failed to saturate MW basis at primes [ 5 ]
    5 After 10 attempts at enlargement, giving up!
    --points not proved 5-saturated,
    5-saturation failed!
    Failed to saturate MW basis at primes [ 5 ]
    (8, 8)
**********************************************************************
File "/nix/store/k9x5qwik8cdr9vm782v5ha116j097qn4-sage-src-9.2/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 1883, in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
Failed example:
    E.simon_two_descent()
Expected:
    (2, 3, [(-1/4 : 2377/8 : 1), (323/4 : 1891/8 : 1)])
Got:
    5 (2, 3, [(-1/4 : 2377/8 : 1), (323/4 : 1891/8 : 1)])
**********************************************************************
1 item had failures:
   2 of  88 in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
    [849 tests, 2 failures, 195.74 s]
```

**Comment by JohnCremona** [comment] 2021-03-01 16:16
Thanks for reporting this.  I had not yet started the process of getting the revised eclib into Sage, and I'llfix what is causing this before I do.  But in any case I wanted to improve the way Sage uses eclib's saturation on elliptic curves.

What the latest change did was precision-related.  In the example you give, eclib is detecing that a point is possibly 5 times a smaller point, and it uses floating point methods to divide by 5.  This will only work if the precision is sufficietly large.  I guess that a call to mwrank.set_precision() before the example here will sort it out, but the issue rams taht this was not needed before.  It's a bit stupid since Sage is better than eclib at dividing points.

I don't know the simplest way to get Sage to use a new version of eclib other than making a whole new spkg, but I should be able to extract the curve and points from this example and test it on eclib outside Sage.  Meanhile I have been running the changed code in this eclib version on several million examples without running into the issue.

**Comment by JohnCremona** [comment] 2021-03-01 16:26
OK, this example runs fine using eclib's tsat program, so the issue is really that Sage does not set merank's precisions sensibly.  When the simon_two_descent() method calls E.saturation() it could set a higher than default precision, but does not.  On the other hand, E.saturation should handle precision itself better than it does.

I prefer not to regard this as an eclib issue, and will make sure that Sage uses eclib better when this version is submitted to Sage.

**Comment by collares** [comment] 2021-03-01 16:26
The relevant curves are `E = EllipticCurve([0, 0, 1, -23737, 960366])` and `E = EllipticCurve([1,0,0,-6664,86543])`. Sorry for not mentioning them earlier!

**Comment by collares** [comment] 2021-03-01 16:31
Great, many thanks for investigating this! I'll close the issue now since it's a Sage issue.

**Comment by JohnCremona** [comment] 2021-03-01 17:03
See https://trac.sagemath.org/ticket/31443

**Comment by JohnCremona** [comment] 2021-03-03 15:12
I am reopening this since I think the best solution will involve more tweaking on the eclib side.

**Comment by JohnCremona** [comment] 2021-03-03 15:15
Incidentally @collares if I think that the current state of the eclib code is worthy of a new release, then I make a release.  The last release is v20190909.  I don't think anyone benefits from regarding every push to the master branch as a formal release.  Secondly, when I do make a new release then I, or some other Sage developer, will update the version of eclib in Sage, and at that point will catch the kind of differences in doctest output which you were doing in your other project.  It seems to me like a waste of human effort for this process to happen twice.

**Comment by collares** [comment] 2021-03-03 15:22
I was under the mistaken impression that tags denoted releases, and I apologize for the extra work. I am helping with packaging for a Linux distribution (NixOS) and we have an auto-update script that operated under the "tags are releases" assumption, so I will find out how to change it to only use actual releases. Thanks for the clarification!

**Comment by JohnCremona** [comment] 2021-03-03 15:31
Fair enough, perhaps I should not add a tag except when I will make a release.  I am not perfectly organised, and one day I will stop making any chages at all to eclib; but that day has not quite yet arrived.

**Comment by collares** [comment] 2021-03-03 15:33
The changes are much appreciated, keep them coming :) It was just a minor confusion on my side. Thanks again for your work!

**Comment by JohnCremona** [comment] 2021-03-04 15:32
I have opened issue #65 for the precision issue with saturation and point division, so can close this again.

**Closed by JohnCremona** 2021-03-04 15:32 UTC

**Comment by JohnCremona** [comment] 2021-03-10 10:37
With apologies to downstreamers, as I am revising the sage-eclib interface after installing eclib-v20210308, I see that despite announcing this as an actual release, it will need to have some minor tweaks made, and there will therefore be another release, probably today.
